# Generated by Django 2.0.7 on 2019-06-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
